var s = new Stack();
    s.push("Manuel");
    s.push("Eduardo");
    s.push("Rios");
        console.log("length: " + s.length());
        console.log(s.peek());
var popped = s.pop();
        console.log("The popped element is: " + popped);
        console.log(s.peek());
    s.push("Martinez");
        console.log(s.peek());
    s.clear();
        console.log("length: " + s.length());
        console.log(s.peek());
    s.push("Clayton");
        console.log(s.peek());
